## File generated by the BNF Converter (bnfc 2.9.5).

# Makefile for building the parser and test program.

GHC        = ghc
GHC_OPTS   = -isrc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc
UNAME 	   = $(shell uname)

# List of goals not corresponding to file names.

.PHONY : all clean distclean lib/runtime.bc

# Default goal.

all : lib/runtime.bc latc latc_llvm

# Rules for building the parser.

Latte/Abs.hs Latte/Lex.x Latte/Par.y Latte/Print.hs : src/Latte.cf
	/home/students/inf/PUBLIC/MRJP/bin/bnfc --haskell -d --functor src/Latte.cf || bnfc --haskell -d --functor src/Latte.cf

Npos/Latte/Abs.hs Npos/Latte/Lex.x Npos/Latte/Par.y Npos/Latte/Print.hs : src/Latte.cf
	/home/students/inf/PUBLIC/MRJP/bin/bnfc -p Npos --haskell -d src/Latte.cf || bnfc -p Npos --haskell -d src/Latte.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

lib/runtime.bc : lib/runtime.ll
	if [ $(UNAME) = Darwin ]; then \
		llvm-as -o lib/runtime.bc lib/runtime_darwin.ll; \
	else \
		llvm-as -o lib/runtime.bc lib/runtime.ll; \
	fi

latc latc_llvm : Latte/Abs.hs Latte/Lex.hs Latte/Par.hs Latte/Print.hs Npos/Latte/Abs.hs Npos/Latte/Lex.hs Npos/Latte/Par.hs Npos/Latte/Print.hs src/TypeChecker.hs src/Instr.hs src/IRCompiler.hs src/Main.hs src/Liveness.hs src/Ssa.hs src/ConstExpr.hs lib/runtime.bc
	${GHC} ${GHC_OPTS} src/Main.hs -o latc_llvm
	${GHC} ${GHC_OPTS} src/Main.hs -o latc

# Rules for cleaning generated files.

clean :
	-rm -f src/*.hi src/*.o src/*.log src/*.aux src/*.dvi
	-rm -rf Latte
	-rm -rf Npos
	-rm latc_llvm
	-rm latc

# EOF
